export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_PENDING = 'CREATE_CATEGORY_PENDING';
export const CREATE_CATEGORY_ERROR = 'CREATE_CATEGORY_ERROR';

export const FETCH_ALL_CATEGORIES_SUCCESS = 'FETCH_ALL_CATEGORIES_SUCCESS';
export const FETCH_ALL_CATEGORIES_PENDING = 'FETCH_ALL_CATEGORIES_PENDING';
export const FETCH_ALL_CATEGORIES_ERROR = 'FETCH_ALL_CATEGORIES_ERROR';