export const FETCH_ALL_PRODUCTS_SUCCESS = 'FETCH_ALL_PRODUCTS_SUCCESS';
export const FETCH_ALL_PRODUCTS_PENDING = 'FETCH_ALL_PRODUCTS_PENDING';
export const FETCH_ALL_PRODUCTS_ERROR = 'FETCH_ALL_PRODUCTS_ERROR';

export const CREATE_PRODUCT_SCCCESS = 'CREATE_PRODUCT_SCCCESS';
export const CREATE_PRODUCT_PENDING = 'CREATE_PRODUCT_SCCCESS';
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';