export const FETCH_ALL_STORES_SUCCESS = 'FETCH_ALL_STORES_SUCCESS';
export const FETCH_ALL_STORES_PENDING = 'FETCH_ALL_STORES_PENDING';
export const FETCH_ALL_STORES_ERROR = 'FETCH_ALL_STORES_ERROR';

export const CREATE_STORE_SUCCESS = 'CREATE_STORE_SUCCESS';
export const CREATE_STORE_PENDING = 'CREATE_STORE_PENDING';
export const CREATE_STORE_ERROR = 'CREATE_STORE_ERROR';

export const FETCH_STORE_BY_ID_SUCCESS = 'FETCH_STORE_BY_ID_SUCCESS';
export const FETCH_STORE_BY_ID_PENDING = 'FETCH_STORE_BY_ID_PENDING';
export const FETCH_STORE_BY_ID_ERROR = 'FETCH_STORE_BY_ID_ERROR';